### Login
POST {{serverUrl}}/auth/login
Content-Type: application/json

{
  "email": "henry@test.com",
  "password": "henry@password"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### Get Profile data
GET {{serverUrl}}/user/profile
Authorization: Bearer {{accessToken}}

### Fail: Get Profile data without accessToken
GET {{serverUrl}}/user/profile