name: Test

on:
  push:
    branches: [main, development, 'feat/**']
  pull_request:
    branches: [main, development]
    types: [opened, synchronize, reopened]

jobs:
  test-verify:
    name: Test & verify the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Compile the project
        run: mvn clean compile

      - name: Test
        run: mvn -B test

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mlangumier_electricity-business-backend

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
            name: test-results
            path: target/surefire-reports